// Copies ABIs from Hardhat artifacts into src/abis.ts. Runs before build when artifacts exist; the generated file is committed.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const artifacts = path.join(here, '..', '..', '..', 'contracts', 'artifacts', 'contracts');
const out = path.join(here, '..', 'src', 'abis.ts');
const targets = [
  ['STREAM_COIN_ABI', 'StreamCoin.sol/StreamCoin.json'],
  ['PAYMENT_ROUTER_ABI', 'PaymentRouter.sol/PaymentRouter.json'],
];

if (process.argv.includes('--if-present') && !fs.existsSync(path.join(artifacts, targets[0][1]))) {
  process.stdout.write('sync-abis: no Hardhat artifacts found, keeping committed src/abis.ts\n');
  process.exit(0);
}

let body = '// AUTO-GENERATED by scripts/sync-abis.mjs from the Hardhat artifacts. Do not edit by hand.\n\n';
for (const [name, rel] of targets) {
  const artifact = JSON.parse(fs.readFileSync(path.join(artifacts, rel), 'utf8'));
  body += `export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
fs.writeFileSync(out, body.trimEnd() + '\n');
process.stdout.write(`sync-abis: wrote ${path.relative(process.cwd(), out)}\n`);
